### PR TITLE
Replace HTML background image with Clojure

### PR DESCRIPTION
**Pull request by Nitive**
Replace HTML background image with Clojure.
Also configure mincer to inline asset path.
Do not see the last commit it is just fix one-space indent in `styles.css`.

### CODE REVIEW

**Comment by Nitive** [comment]
See result here — http://81e28750.ngrok.io
_(_

**Comment by Nitive** [comment]
Oops, close it accidentally.

**Comment by sashashakun** [comment]
Cool, thanks! Will merge it after #67

**Comment by sashashakun** [comment]
@Nitive need rebase

**Comment by Nitive** [comment]
Rebased. It was few eslint errors in `app.js`. Tests have passed because we did not have `app.js` in lint script. I fixed it.

**Comment by gldmtr** [comment]
@Nitive можешь ли в app.js вместо 
`sequelize.sync({ force: true }).then(() => {`
написать что-нибудь типа 

`const force = process.env.NODE_ENV !== 'production';
sequelize.sync({ force }).then(() => {`

**Comment by sashashakun** [comment]
@Nitive i'm very sorry, but you need to rebase one more time, because of very very hot fix #90 🤕

**Comment by Nitive** [comment]
Done

**Pull request merged**
